import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Red_Hat_Display } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const redHatDispaly = Red_Hat_Display({ weight: "400", subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Fitnesso",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${redHatDispaly.className} bg-[#dddddd] text-[#081158]`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
